---
inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  voxpupuli-rubocop: rubocop.yml

Layout/LineLength:
  Exclude:
    - acceptance/**/*.rb
    - spec/**/*.rb

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - acceptance/**/acceptance-options.rb

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - acceptance/fixtures/module/spec/**/*.rb

RSpec/FilePath:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style:
  Enabled: false
