name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  rubocop:
    env:
      BUNDLE_WITHOUT: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop

  test:
    # CentOS 7 testing is broken on Ubuntu 22.04
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "2.7"
          - ruby: "3.0"
          - ruby: "3.1"
          - ruby: "3.2"
            coverage: "yes"
    env:
      COVERAGE: ${{ matrix.coverage }}
      BUNDLE_WITHOUT: release:rubocop
      BEAKER_HYPERVISOR: docker
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build gem
        run: gem build *.gemspec
      - name: Run unit tests
        run: bundle exec rake spec
      - name: Run acceptance tests
        run: bundle exec rake acceptance
